### ISSUE TITLE
repeating exit 1 appears in terminal.

### ISSUE THREAD

**Issue by iladin** [psprint/zconvey#1]
Just wanted to make you aware of the following [issue ](https://gitlab.com/iladin/dotfiles/issues/4)I'm having

![image](https://cloud.githubusercontent.com/assets/3768247/18610869/ba588a9e-7cdc-11e6-88ae-3ab7e23d656c.png)

I have lots of broken stuff in my dotfiles at the moment (I need to fix the complete command not found)

### Steps to reproduce

1. Click the link below
[![Contribute](http://beta.codenvy.com/factory/resources/codenvy-contribute.svg)](http://beta.codenvy.com/f?url=https://gitlab.com/iladin/dotfiles)

2. Start a new terminal

![image](https://cloud.githubusercontent.com/assets/3768247/18610898/b3ee8a5e-7cdd-11e6-8938-2ae57fb9fc01.png)

3. Type in zsh

I'm not quite sure what is causing it, any ideas?

**Comment by iladin** [comment]
FYI, thanks for everything you've done for the zsh community.

**Comment by psprint** [comment]
Thank you for the thanks, I hope my software will make some use.

The issue was: once in 2 seconds (when keyboard isn't active) Zconvey checks for input data. It's a fast-track, quick -e test. I've mistakenly chosen to return "1" then, but it isn't an error situation, "0" should be returned. Fixed, thanks!

Wonder if you like the logo. It can be changed to text or disabled ("none") with:

```zsh
zstyle ":plugin:zconvey" greeting "text"
```

Maybe you would like to be an early adopter of an upcoming plugin: zaccumulator. After loading, run __from-zhistory-accumulate, then accumulator is available under Ctrl-B, few moves should tell what's going on :) Few new modules are coming for the plugin, currently there are three betas: shell utils, vim, emacs.

**Comment by iladin** [comment]
Confirmed fixed.  

Thank you.
